title: Nick Walker
first_last_name: Nick Walker
email: nick@nickwalker.us
description: > # this means to ignore newlines until "baseurl:"
  Computer science student at the University of Washington with interests in robotics, interactive machine learning and digital media.
baseurl: "" # Subpath, in my case, root
url: "https://nickwalker.us" # includes protocol
google_analytics: "UA-30066313-1"

# Bio information
twitter_username: nickwalker_us
github_username:  nickswalker
linkedin_username: niwalker
flickr_username: nickwalker-us
gravatar_url: https://www.gravatar.com/avatar/05a17826262b803bdc53a402751c884e

permalink: /blog/:year/:month/:title

# Custom collections
collections_dir: collections
collections:
  projects:
    output: true
    permalink: projects/:title
  research:
    output: true
    permalink: research/:title

# Archive listings for blog
jekyll-archives:
  enabled: ['year', 'month']
  layout: 'archive'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# bibtex rendering
scholar:
  bibliography_template: 'bib_entry'
  source: '/_data'
  details_layout: 'bib_details.html'
  reference_tagname: 'p'
  details_link: ""

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project_entry
      featured: false
      has_article: true
      custom_js:
      - "https://code.jquery.com/jquery-3.1.1.min.js"
      - "/assets/js/jquery.fancybox.min.js"
      - "/assets/js/initialize-fancybox.js"
      custom_css:
      - "/assets/css/jquery.fancybox.min.css"

# Build settings
markdown: kramdown
# theme: research-portfolio
plugins:
- jekyll-archives
- jekyll-compose
- jekyll-feed
- jekyll-redirect-from
- jekyll-scholar
- jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .idea
include:
  - .well-known
