title: Nick Walker
first_last_name: Nick Walker
email: nick@nickwalker.us
description: > # this means to ignore newlines until "baseurl:"
  Human-centered roboticist.
baseurl: "" # Subpath, in my case, root
url: "https://nickwalker.us" # includes protocol

# Bio information
acm_dl_id: 99659508800
arxiv_id: walker_n_1
dblp_id: 14/1613-1
flickr_username: nickwalker-us
github_username:  nickswalker
google_scholar_id: JYaJjE8AAAAJ
gravatar_url: https://www.gravatar.com/avatar/05a17826262b803bdc53a402751c884e
hackernews_username: nickswalker
ieee_spectrum_id: nick-walker
ieeexplore_id: 37086573897
keybase_username: nickswalker
linkedin_username: niwalker
mastodon_username: nickwalker
mastodon_instance: sigmoid.social
openreview_id: "~Nick_Walker1"
openstreetmap_username: nickswalker
orcid_id: 0000-0001-7711-0003
semantic_scholar_id: Nick-Walker/145314605
stackoverflow_id: 1497463/nick-walker
strava_id: 35387878
wikidata_id: Q130865802
web_of_science_id: AEX-3927-2022
youtube_username: "@WalkerSNick"

# trailing slash -> index.html. Note that jekyll scholar bases its behavior on the trailing slash here
permalink: /blog/:year/:title/

# Custom collections
collections_dir: collections
collections:
  projects:
    output: true
    permalink: projects/:title/
  research:
    output: true
    permalink: research/:title/

# Archive listings for blog
jekyll-archives:
  enabled: ['year']
  layouts:
    year: 'bounce_link'
  permalinks:
    year: '/blog/:year/'

# bibtex rendering
scholar:
  bibliography: "publications.bib"
  bibliography_template: 'bib_entry'
  bibliography_list_attributes:
    reversed: "reversed"
  source: '/_data'
  style: ieee-with-url
  details_layout: 'bib_details.html'
  reference_tagname: 'p'
  details_link: ""
  details_dir: "publications"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author:
        name: Nick Walker
        url: https://nickwalker.us
      layout: post
      custom_js:
        - "https://code.jquery.com/jquery-3.1.1.min.js"
        - "/assets/js/jquery.fancybox.min.js"
        - "/assets/js/initialize-fancybox.js"
      custom_css:
        - "/assets/css/jquery.fancybox.min.css"
  - scope:
      path: ""
      type: projects
    values:
      layout: project_entry
      redirect_to: "must_specify_redirect_on_project" # Should cause HTML proofer to fail for these article-less entries
      custom_js:
      - "https://code.jquery.com/jquery-3.1.1.min.js"
      - "/assets/js/jquery.fancybox.min.js"
      - "/assets/js/initialize-fancybox.js"
      custom_css:
      - "/assets/css/jquery.fancybox.min.css"

# Build settings
markdown: kramdown
# theme: research-portfolio
plugins:
- jekyll-archives
- jekyll-compose
- jekyll-feed
- jekyll-redirect-from
- jekyll-scholar
- jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .idea
include:
  - .well-known
