title: Nick Walker
first_last_name: Nick Walker
email: nick@nickwalker.us
description: > # this means to ignore newlines until "baseurl:"
  Computer science student at UT Austin with interests spanning reinforcement learning, interactive machine learning and digital media.
baseurl: "" # Subpath, in my case, root
url: "https://nickwalker.us" # includes protocol
google_analytics: "UA-30066313-1"

# Bio information
twitter_username: nickwalker.us
github_username:  nickswalker
linkedin_username: niwalker
google_plus_profile_url: https://plus.google.com/109675278505943174152/
gravatar_url: https://www.gravatar.com/avatar/05a17826262b803bdc53a402751c884e

# Custom collections
collections:
  projects:
    output: true
    permalink: projects/:title
  publications:
    output: true


defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      featured: false
      has_article: true
      custom_js:
      - "https://code.jquery.com/jquery-3.1.1.min.js"
      - "/assets/js/jquery.fancybox.min.js"
      - "/assets/js/initialize-fancybox.js"
      custom_css:
      - "/assets/css/jquery.fancybox.min.css"
  - scope:
      path: ""
      type: publications
    values:
      layout: publication

# Build settings
markdown: kramdown
# theme: research-portfolio
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gallery-generator
exclude:
  - Gemfile
  - Gemfile.lock


gallery:
  dir: photos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
